spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_produtos
spring.datasource.username=postgres
spring.datasource.password=Mcartney42!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc=DEBUG